# This file was generated by GoReleaser. DO NOT EDIT.
cask "human" do
  name "human"
  desc "Issue tracker CLI for AIs"
  homepage "https://github.com/gethuman-sh/human"
  version "0.20.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "human"

  on_macos do
    on_intel do
      url "https://github.com/gethuman-sh/human/releases/download/v#{version}/human_#{version}_darwin_amd64.tar.gz"
      sha256 "f0a6aaafbcdc80ed15b61fd6b009585f7b94c7dab545f6c6fa0c9a7264d35d7e"
    end
    on_arm do
      url "https://github.com/gethuman-sh/human/releases/download/v#{version}/human_#{version}_darwin_arm64.tar.gz"
      sha256 "8689df4c5ec98b5f43e7e917f7e54bc207e8350c0d7d790ad112799668a74412"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gethuman-sh/human/releases/download/v#{version}/human_#{version}_linux_amd64.tar.gz"
      sha256 "67770db3f063c0ef9ebaa423a29131cbd6b7bc780705742bfa62354fc736b9bf"
    end
    on_arm do
      url "https://github.com/gethuman-sh/human/releases/download/v#{version}/human_#{version}_linux_arm64.tar.gz"
      sha256 "8679ffab8ed39bd2bbe179af0c12c96a77642c24dc953bcf03274a77629cfb67"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/human"]
    end
  end

  # No zap stanza required
end
